### ISSUE TITLE
holiday flight seems that it would return a cargo instance.

### ISSUE THREAD

**Issue by nicky-ayoub** [ocharles/OCharles-Blog-Factories#1]
I didn't test the code, but by reading it, I think

my $holiday_flight = FlightFactory->new_flight({ cargo => [qw( Bob Tom )] });

should be 

my $holiday_flight = FlightFactory->new_flight({ passengers => [qw( Bob Tom )] });

**Comment by ocharles** [comment]
I'm no longer writing Perl or maintaining this blog, so I will have to close this issue. Sorry, but thanks for the comment.
